<a href="https://colab.research.google.com/github/Karsuman4298/Deep-learning/blob/main/PyTorch_training_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#The torch.nn.Module is the fundamental base class for all neural network modules in PyTorch, providing the building blocks and essential functionality for creating and managing network architectures.

#Key Functions and Features
Base Class for Models and Layers: Both entire neural networks and individual layers (like nn.Linear or nn.Conv2d) are subclasses of nn.Module. This allows for a nested, modular structure for building complex architectures.


#Parameter Management:

 Subclassing nn.Module aut#omatically tracks all learnable parameters (weights and biases) defined within the model, making them accessible via the .parameters() method.
 Forward Pass Definition: You must override the forward(self, x) method to define how input data x flows through the network's layers and computations.

#Device Management:
It provides convenient methods like .to(device) to easily move the entire model and its parameters between the CPU and GPU (CUDA).


#Integration with Autograd:
 nn.Module works seamlessly with PyTorch's automatic differentiation engine (autograd), which computes gradients for parameters during backpropagation.
Standardized Workflow: It enables the use of standard training loop steps such as model.zero_grad(), loss.backward(), and optimizer.step().

#Serialization:
 Modules are easy to save and restore, which is essential for checkpoints and model deployment.

In [28]:
import numpy as np
import pandas as pd
import torch
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import S

In [29]:
# Install dependencies as needed:
# pip install kagglehub[pandas-datasets]
import kagglehub
from kagglehub import KaggleDatasetAdapter

# Set the path to the file you'd like to load
file_path = "data.csv"

# Load the latest version
df = kagglehub.load_dataset(
  KaggleDatasetAdapter.PANDAS,
  "uciml/breast-cancer-wisconsin-data",
  file_path,
  # Provide any additional arguments like
  # sql_query or pandas_kwargs. See the
  # documenation for more information:
  # https://github.com/Kaggle/kagglehub/blob/main/README.md#kaggledatasetadapterpandas
)

/tmp/ipykernel_407/1647292472.py:10: DeprecationWarning: Use dataset_load() instead of load_dataset(). load_dataset() will be removed in a future version.
  df = kagglehub.load_dataset(

Using Colab cache for faster access to the 'breast-cancer-wisconsin-data' dataset.

In [30]:
df

           id diagnosis  ...  fractal_dimension_worst  Unnamed: 32
0      842302         M  ...                  0.11890          NaN
1      842517         M  ...                  0.08902          NaN
2    84300903         M  ...                  0.08758          NaN
3    84348301         M  ...                  0.17300          NaN
4    84358402         M  ...                  0.07678          NaN
..        ...       ...  ...                      ...          ...
564    926424         M  ...                  0.07115          NaN
565    926682         M  ...                  0.06637          NaN
566    926954         M  ...                  0.07820          NaN
567    927241         M  ...                  0.12400          NaN
568     92751         B  ...                  0.07039          NaN

[569 rows x 33 columns]

In [31]:
df.shape

(569, 33)

In [32]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   id                       569 non-null    int64
 1   diagnosis                569 non-null    object
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             569 non-null    float64
 15  area_se                  569 non-null    float64
 16  smoothness_se            569 non-null    float64
 17  compactness_se           569 non-null    float64
 18  concavity_se             569 non-null    float64
 19  concave points_se        569 non-null    float64
 20  symmetry_se              569 non-null    float64
 21  fractal_dimension_se     569 non-null    float64
 22  radius_worst             569 non-null    float64
 23  texture_worst            569 non-null    float64
 24  perimeter_worst          569 non-null    float64
 25  area_worst               569 non-null    float64
 26  smoothness_worst         569 non-null    float64
 27  compactness_worst        569 non-null    float64
 28  concavity_worst          569 non-null    float64
 29  concave points_worst     569 non-null    float64
 30  symmetry_worst           569 non-null    float64
 31  fractal_dimension_worst  569 non-null    float64
 32  Unnamed: 32              0 non-null      float64
dtypes: float64(31), int64(1), object(1)
memory usage: 146.8+ KB

In [33]:
df.drop(columns=['id','Unnamed: 32'],inplace=True)
df

    diagnosis  radius_mean  ...  symmetry_worst  fractal_dimension_worst
0           M        17.99  ...          0.4601                  0.11890
1           M        20.57  ...          0.2750                  0.08902
2           M        19.69  ...          0.3613                  0.08758
3           M        11.42  ...          0.6638                  0.17300
4           M        20.29  ...          0.2364                  0.07678
..        ...          ...  ...             ...                      ...
564         M        21.56  ...          0.2060                  0.07115
565         M        20.13  ...          0.2572                  0.06637
566         M        16.60  ...          0.2218                  0.07820
567         M        20.60  ...          0.4087                  0.12400
568         B         7.76  ...          0.2871                  0.07039

[569 rows x 31 columns]

In [34]:
df.shape

(569, 31)

In [37]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.drop(columns=['diagnosis']),df['diagnosis'],test_size=0.2,random_state=42)

In [38]:
X_train

     radius_mean  texture_mean  ...  symmetry_worst  fractal_dimension_worst
68         9.029         17.33  ...          0.4228                  0.11750
181       21.090         26.57  ...          0.4098                  0.12840
63         9.173         13.86  ...          0.3282                  0.08490
248       10.650         25.22  ...          0.3409                  0.08147
60        10.170         14.88  ...          0.3557                  0.08020
..           ...           ...  ...             ...                      ...
71         8.888         14.64  ...          0.2254                  0.10840
106       11.640         18.33  ...          0.2806                  0.09097
270       14.290         16.82  ...          0.2458                  0.06120
435       13.980         19.62  ...          0.3179                  0.10550
102       12.180         20.52  ...          0.2694                  0.06878

[455 rows x 30 columns]

In [40]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [41]:
X_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [42]:
y_train

68     B
181    M
63     B
248    B
60     B
      ..
71     B
106    B
270    B
435    M
102    B
Name: diagnosis, Length: 455, dtype: object

In [43]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

In [44]:
y_train

array([0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1,
       1, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 1, 1, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 0])

In [50]:
X_train_tensors=torch.from_numpy(X_train.astype(np.float64))
X_test_tensors=torch.from_numpy(X_test.astype(np.float64))
y_train_tensors=torch.from_numpy(y_train.astype(np.float64))
y_test_tensors=torch.from_numpy(y_test.astype(np.float64))

In [51]:
X_train_tensors

tensor([[-1.4408, -0.4353, -1.3621,  ...,  0.9320,  2.0972,  1.8865],
        [ 1.9741,  1.7330,  2.0917,  ...,  2.6989,  1.8912,  2.4978],
        [-1.4000, -1.2496, -1.3452,  ..., -0.9702,  0.5976,  0.0579],
        ...,
        [ 0.0488, -0.5550, -0.0651,  ..., -1.2390, -0.7086, -1.2715],
        [-0.0390,  0.1021, -0.0314,  ...,  1.0500,  0.4343,  1.2134],
        [-0.5486,  0.3133, -0.6035,  ..., -0.6110, -0.3345, -0.8463]],
       dtype=torch.float64)

In [52]:
y_train_tensors

tensor([0., 1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 1., 1.,
        0., 0., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 0., 1., 1., 1., 0.,
        1., 0., 0., 0., 0., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 1., 1.,
        0., 0., 1., 0., 1., 0., 0., 0., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0.,
        1., 1., 0., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 1., 0.,
        1., 1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1.,
        0., 0., 1., 0., 1., 0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 1., 0., 1.,
        0., 1., 0., 1., 0., 0., 1., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0.,
        1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 1., 0., 1.,
        0., 0., 0., 1., 0., 1., 1., 0., 0., 1., 0., 1., 1., 1., 0., 0., 0., 1.,
        0., 0., 1., 0., 1., 0., 0., 0., 1., 0., 1., 0., 0., 1., 1., 0., 0., 1.,
        0., 1., 1., 0., 1., 1., 0., 0., 1., 1., 1., 0., 0., 0., 0., 1., 0., 1.,
        1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 0., 1., 1., 0., 0., 1., 0., 0.,
        0., 0., 0., 1., 0., 0., 1., 1., 0., 1., 0., 1., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 1., 0., 0., 0., 0., 0., 0., 1., 0., 0., 1., 0., 1., 1., 1.,
        0., 1., 0., 0., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        1., 0., 0., 1., 1., 0., 1., 0., 1., 1., 0., 0., 1., 0., 1., 1., 0., 1.,
        1., 0., 0., 1., 0., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0., 0., 1.,
        1., 0., 1., 1., 0., 0., 0., 1., 0., 1., 1., 1., 1., 0., 0., 1., 0., 0.,
        1., 1., 1., 1., 1., 1., 0., 0., 0., 0., 0., 0., 0., 1., 1., 1., 1., 0.,
        0., 0., 0., 1., 0., 1., 0., 0., 0., 0., 0., 1., 1., 1., 0., 0., 1., 0.,
        0., 1., 1., 1., 1., 0., 0., 1., 1., 0., 0., 0., 1., 1., 1., 0., 0., 1.,
        0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0., 0., 1., 0., 0., 1., 0., 0., 1., 1., 1., 0., 1., 1., 0., 1., 0.,
        0., 0., 0., 1., 0.], dtype=torch.float64)

In [53]:
y_test_tensors.shape

torch.Size([114])

In [54]:
X_train_tensors.shape

torch.Size([455, 30])

In [71]:
class simpleNN():

  def __init__(self,x):
    self.weights=torch.rand(X_train_tensors.shape[1],1,requires_grad=True,dtype=torch.float64)
    self.bias=torch.zeros(1,requires_grad=True,dtype=torch.float64)


  def forward(self,x):
    z=torch.matmul(x,self.weights)+ self.bias
    y_pred=torch.sigmoid(z)
    return y_pred

#Parameters

In [103]:
lr=0.01
epoch=40

In [104]:
model=simpleNN(X_train_tensors)

In [105]:
model.weights

tensor([[0.8485],
        [0.3880],
        [0.8770],
        [0.5587],
        [0.2406],
        [0.0837],
        [0.9370],
        [0.4089],
        [0.2019],
        [0.2481],
        [0.5260],
        [0.9765],
        [0.0435],
        [0.0262],
        [0.1344],
        [0.6190],
        [0.4263],
        [0.4328],
        [0.4441],
        [0.7149],
        [0.6099],
        [0.2599],
        [0.2271],
        [0.3030],
        [0.6034],
        [0.5097],
        [0.3003],
        [0.7231],
        [0.5306],
        [0.1247]], dtype=torch.float64, requires_grad=True)

In [106]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

#Training Pipelines

In [107]:
#create model
model=simpleNN(X_train_tensors)

#define loop
for i in range(epoch):
  #forward pass

  y_pred=model.forward(X_train_tensors)

#loss calculate
  loss=torch.nn.functional.binary_cross_entropy(y_pred,y_train_tensors.view(-1,1))
  print(f'epoch: {i+1} loss: {loss}')


#backward pass
  loss.backward()
# Parameter updates
  with torch.no_grad():

   model.weights -= lr * model.weights.grad
   model.bias -= lr * model.bias.grad

#print loss for each epoch
  print(f'epoch: {i+1} loss: {loss}')

epoch: 1 loss: 0.6388484366846123
epoch: 1 loss: 0.6388484366846123
epoch: 2 loss: 0.6366981607542403
epoch: 2 loss: 0.6366981607542403
epoch: 3 loss: 0.632408992630214
epoch: 3 loss: 0.632408992630214
epoch: 4 loss: 0.6260036562195843
epoch: 4 loss: 0.6260036562195843
epoch: 5 loss: 0.6175161311669166
epoch: 5 loss: 0.6175161311669166
epoch: 6 loss: 0.6069915483693152
epoch: 6 loss: 0.6069915483693152
epoch: 7 loss: 0.5944860814811532
epoch: 7 loss: 0.5944860814811532
epoch: 8 loss: 0.580066879104814
epoch: 8 loss: 0.580066879104814
epoch: 9 loss: 0.5638121062562356
epoch: 9 loss: 0.5638121062562356
epoch: 10 loss: 0.545811192473669
epoch: 10 loss: 0.545811192473669
epoch: 11 loss: 0.5261654306435911
epoch: 11 loss: 0.5261654306435911
epoch: 12 loss: 0.5049891325465578
epoch: 12 loss: 0.5049891325465578
epoch: 13 loss: 0.48241161614964057
epoch: 13 loss: 0.48241161614964057
epoch: 14 loss: 0.45858027373603905
epoch: 14 loss: 0.45858027373603905
epoch: 15 loss: 0.4336644144827887
epoch: 15 loss: 0.4336644144827887
epoch: 16 loss: 0.4078576488981234
epoch: 16 loss: 0.4078576488981234
epoch: 17 loss: 0.38137360369246803
epoch: 17 loss: 0.38137360369246803
epoch: 18 loss: 0.35443151575217163
epoch: 18 loss: 0.35443151575217163
epoch: 19 loss: 0.32724183798499235
epoch: 19 loss: 0.32724183798499235
epoch: 20 loss: 0.30001151287519584
epoch: 20 loss: 0.30001151287519584
epoch: 21 loss: 0.27296857117226203
epoch: 21 loss: 0.27296857117226203
epoch: 22 loss: 0.24638232655774783
epoch: 22 loss: 0.24638232655774783
epoch: 23 loss: 0.2205626311158415
epoch: 23 loss: 0.2205626311158415
epoch: 24 loss: 0.19585441347056717
epoch: 24 loss: 0.19585441347056717
epoch: 25 loss: 0.17269838017152642
epoch: 25 loss: 0.17269838017152642
epoch: 26 loss: 0.1518418222971896
epoch: 26 loss: 0.1518418222971896
epoch: 27 loss: 0.1343893036343131
epoch: 27 loss: 0.1343893036343131
epoch: 28 loss: 0.12081490604488353
epoch: 28 loss: 0.12081490604488353
epoch: 29 loss: 0.1105728338504145
epoch: 29 loss: 0.1105728338504145
epoch: 30 loss: 0.10290749093756223
epoch: 30 loss: 0.10290749093756223
epoch: 31 loss: 0.0971937964601862
epoch: 31 loss: 0.0971937964601862
epoch: 32 loss: 0.09301793473827347
epoch: 32 loss: 0.09301793473827347
epoch: 33 loss: 0.09014614458228888
epoch: 33 loss: 0.09014614458228888
epoch: 34 loss: 0.08846373052881924
epoch: 34 loss: 0.08846373052881924
epoch: 35 loss: 0.08793058176538046
epoch: 35 loss: 0.08793058176538046
epoch: 36 loss: 0.08855544171992384
epoch: 36 loss: 0.08855544171992384
epoch: 37 loss: 0.09038433480122529
epoch: 37 loss: 0.09038433480122529
epoch: 38 loss: 0.09350116552565685
epoch: 38 loss: 0.09350116552565685
epoch: 39 loss: 0.09803803658162696
epoch: 39 loss: 0.09803803658162696
epoch: 40 loss: 0.10418333908344388
epoch: 40 loss: 0.10418333908344388

In [108]:
model.weights

tensor([[ 0.6126],
        [ 0.5183],
        [ 0.6865],
        [ 0.5749],
        [ 0.3512],
        [ 0.3446],
        [-0.0802],
        [ 0.5632],
        [ 0.1170],
        [-0.7718],
        [ 0.6821],
        [-0.0450],
        [ 0.6438],
        [ 0.9328],
        [-0.1130],
        [-0.5378],
        [-0.5534],
        [-0.5980],
        [ 0.2780],
        [-0.6802],
        [ 0.9455],
        [ 0.7561],
        [ 1.2073],
        [ 0.8338],
        [ 0.3376],
        [ 0.0580],
        [ 0.6359],
        [ 0.3927],
        [ 0.4942],
        [ 0.1989]], dtype=torch.float64, requires_grad=True)

In [109]:
model.bias

tensor([-0.2157], dtype=torch.float64, requires_grad=True)

# Evaluation

In [110]:
with torch.no_grad():
  y_pred=model.forward(X_test_tensors)
  y_pred=(y_pred>0.5).float()
  accuracy=(y_pred==y_test_tensors.view(-1,1)).float().mean()
  print(f'accuracy: {accuracy}')

accuracy: 0.9912280440330505